version: 2.0

jobs:
  go:
    docker:
      - image: cimg/go:1.10.8
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./go/run_tests
  python:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Run Tests
          command: ./python/run_tests

workflows:
  version: 2
  build:
    jobs:
      - python
      - go
