version: 2.0

jobs:
  go:
    docker:
      - image: circleci/golang:1.17.5
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./go/run_tests
  python:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./python/run_tests

workflows:
  version: 2
  build:
    jobs:
      - python
      - go
